name: ChatGPT Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  chatgpt-review:
    runs-on: ubuntu-latest

    steps:
      - name: The Code Reviewer
        uses: rileyeh/github-chatgpt-integration@v1.0
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-pr-id: ${{ github.event.number }}
